# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbae448fbae448fbae448
  facebook_api_id: <%= ENV["DEV_FACEBOOK_API_ID"] %>
  facebook_api_secret: <%= ENV["DEV_FACEBOOK_API_SECRET"] %>
  twitter_api_id: <%= ENV["DEV_TWITTER_API_ID"] %>
  twitter_api_secret: <%= ENV["DEV_TWITTER_API_SECRET"] %>
  google_api_id: <%= ENV["DEV_GOOGLE_API_ID"] %>
  google_api_secret: <%= ENV["DEV_GOOGLE_API_SECRET"] %>

test:
  secret_key_base: e4dfde8a4ac1f9b257af3e709c8a6544f6896bbbd8f0804f120c47a836220236e0ea158b793de6e67c6e0c2be2d197c5f367e9160648d85547286199856d5f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["PROD_SECRET_KEY_BASE"] %>
  facebook_api_id: <%= ENV["PROD_FACEBOOK_API_ID"] %>
  facebook_api_secret: <%= ENV["PROD_FACEBOOK_API_SECRET"] %>
  twitter_api_id: <%= ENV["PROD_TWITTER_API_ID"] %>
  twitter_api_secret: <%= ENV["PROD_TWITTER_API_SECRET"] %>
  google_api_id: <%= ENV["PROD_GOOGLE_API_ID"] %>
  google_api_secret: <%= ENV["PROD_GOOGLE_API_SECRET"] %>
